### ISSUE TITLE
Segfaults on last git version

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/skhd#13]
I guess this is related to the Os vs O2 optimization, but last git version (a746b3451fe1e811f490df6f30d29250be284a65) is segfaulting:

```
skhd: using config '/Users/bigo/.skhdrc'
(#2) hotkey :: {
	mod: 'cmd'
	mod: 'alt'
	key: 'q' (0x0c)
[1]    98392 segmentation fault  skhd
```

**Comment by koekeishiya** [comment]
I assume this is still installed using homebrew?

**Comment by koekeishiya** [comment]
I can reproduce this with the homebrew install, but I cannot reproduce the problem by building manually with `-0s`. Prior to the fix in #7, I could reproduce with `-0s`. This makes me thing the hmoebrew build settings differ in other aspects than just the optimization level.

I'm going to try and override the homebrew formulae to build with `-03` and if that does not fix it, I will be removing the homebrew option.

This is just stupid; e.g https://github.com/koekeishiya/skhd/commit/e1e8a631ad6e312ba6e446b0f8adcf815c0fab70 this change fixed the segfault in #7. 

These issues seems to be caused by aggressive compilation settings, and it is not something I can reliably debug as it is directly connected to the compilers code generation.

**Comment by koekeishiya** [comment]
Updated homebrew formulae.

**Comment by crisidev** [comment]
I can confirm, v 0.0.10 work fine. Thanks for the quick fix.

**Comment by snwflake** [comment]
As much as I want to avoid reopening this Issue......

```
skhd: using config '/Users/snwFlake/.skhdrc'
(#34) hotkey :: {
	mod: 'alt'
[1]    50367 segmentation fault  skhd
```
```
Sierra 10.12.6
Homebrew 1.3.5
skhd 0.0.10
clang 800.0.42.1
no gcc installed
```
