### ISSUE TITLE
Help for a newbie

### ISSUE THREAD

**Issue by azapicoe** [koekeishiya/skhd#14]
Hi, first of all thank you koekeishiya for your work and your two awesome wm.
I have a stupid question, how can i override native macos hotkeys with shkd ones. I know that i can disable some of them in preferences, but i dont find the option with others like hidding (cmd + h) and i want it for focus the left window!

**Comment by koekeishiya** [comment]
*skhd* will override macOS hotkeys by default. All you have to do is register it as a bind.

Adding: `cmd - h : chunkc tiling::window --focus west` in your *~/.skhdrc* will make *cmd - h* focus the left window instead of hiding an application, assuming *chunkwm* is running. If *chunkwm* is not running, it will still prevent macOS *cmd - h* from triggering.

You also need to make sure that *skhd* is running on your system, or the config will have no effect.

**Comment by azapicoe** [comment]
Done, it was my mistake . Nice to know that this is enabled by default. Thanks :)

**Comment by yigitkonur** [comment]
It does not override since Mojave release to Big Sur: https://github.com/koekeishiya/skhd/pull/50
Just want to update here.
