### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by stevebasford** [koekeishiya/skhd#17]
I'm on macos highsierra trying to run skhd with chunkwm. Chunkwm is working fine but skhd doesn't seem to be registering any keypresses for anything. I've copied the default configs and the process is showing as running in `brew services list`. I can't see either a skhd.out or skhd.err in the /tmp directory. Please advise.

**Comment by koekeishiya** [comment]
I believe you have to install using the brew option *--with-logging*. Alternatively, you can try to run *skhd* directly from a terminal and it will show any potential error message.

I believe the issue is that something is keeping "Secure Keyboard Entry" enabled on your system.
This should trigger the error here: https://github.com/koekeishiya/skhd/blob/master/src/skhd.c#L178

Note the following prerequisite from the readme:
```
The first time skhd is ran, it will request access to the accessibility API.

After access has been granted, the application must be restarted.

Secure Keyboard Entry must be disabled for skhd to receive key-events.
```

**Comment by stevebasford** [comment]
Managed to get it going, I think something funny was going on with the accessibility api like you said.

**Comment by k4k** [comment]
@stevebasford Can you please provide some details with how you fixed this? I've been struggling for the last few hours trying to get this working myself. I've installed `skhd` with homebrew using `brew install --HEAD --with-logging skhd` and when I run `brew services start skhd` the first time I'm prompted to allow it access to the accessibility API. I allow it, close the settings screen and then run `brew services restart skhd`. No further errors are printed to `/usr/local/var/log/skhd/skhd.err.log`. I am not sure how `skhd` is supposed to run but I do not see any processes for it with `ps aux | grep skhd`. Revoking the accessibility api access, however, while it's still supposedly running causes a prompt to enable it again and an entry in the `skhd.error.log` file so something must be running.

I am using `chunkwm` in conjunction with `skhd`. Invoking `chunkc` commands manually does work so I believe the issue is with skhd not overriding MacOS keybindings. I'm just not sure where to get additional log information to aid in debugging this.

**Comment by gnohz** [comment]
@k4k I had similar problems, and fixed it by running "skhd" in the terminal. Hope it helps.

**Comment by stevebasford** [comment]
@k4k Sorry I've just seen this an can't remember. Are you still having problems? If so I'll try have a think.

**Comment by k4k** [comment]
@stevebasford If you think of it let me know but for now I've given up. Too much real work to do.

**Comment by nrolland** [comment]
How did you launch it from the command line ?
I added it to the accessibility database and enabled it, to no avail

I wish to see a log of the interpreted keys when captured by skhd (is it otherwise possible ?)

```

nrolland@mactoasty ~ $ sudo tccutil --list -v                                                                                                                                                                                                                                                                                                        [ruby-2.3.3p222]
Password:
Opening Database...
Database opened.

Fetching Entries from Database...

/usr/local/opt/chunkwm/bin/chunkwm
com.apple.Terminal
com.getdropbox.dropbox
com.google.Keystone.Agent
com.googlecode.iterm2
com.kapeli.dashdoc
com.manytricks.witchdaemon

nrolland@mactoasty ~ $ sudo tccutil --insert $(whence -p skhd)                                                                                                                                                                                                                                                                                       [ruby-2.3.3p222]
nrolland@mactoasty ~ $ sudo tccutil --list -v                                                                                                                                                                                                                                                                                                        [ruby-2.3.3p222]
Opening Database...
Database opened.

Fetching Entries from Database...

/usr/local/bin/skhd
/usr/local/opt/chunkwm/bin/chunkwm
com.apple.Terminal
com.getdropbox.dropbox
com.google.Keystone.Agent
com.googlecode.iterm2
com.kapeli.dashdoc
com.manytricks.witchdaemon

nrolland@mactoasty ~ $ sudo tccutil --enable $(whence -p skhd)                                                                                                                                                                                                                                                                                       [ruby-2.3.3p222]
nrolland@mactoasty ~ $ sudo tccutil --list -v                                                                                                                                                                                                                                                                                                        [ruby-2.3.3p222]
Opening Database...
Database opened.

Fetching Entries from Database...

/usr/local/bin/skhd
/usr/local/opt/chunkwm/bin/chunkwm
com.apple.Terminal
com.getdropbox.dropbox
com.google.Keystone.Agent
com.googlecode.iterm2
com.kapeli.dashdoc
com.manytricks.witchdaemon

nrolland@mactoasty ~ $ /usr/local/bin/skhd                                                                                                                                                                                                                                                                                                           [ruby-2.3.3p222]
skhd: must be run with accessibility access! abort..
nrolland@mactoasty ~ $
```

**Comment by braham-snyder** [comment]
Ran into this after updating to Big Sur, but fairly certain I fixed it now.

Like @gnohz mentioned, `skhd` worked fine when I stopped the `brew` service and started it directly from my terminal instead. So then I tried removing `skhd`'s accessibility permission, restarted the service, re-added the accessibility permission, and now it works fine again.
