### ISSUE TITLE
Can't hotload config file if it is a symlink

### ISSUE THREAD

**Issue by edwild22** [koekeishiya/skhd#19]
Great project! I'm on Mac OSX 10.11 and using skhd to control chunkwm.

If ~/.skhdrc is a symlink, then it can't hotload the config file, and I have to do `brew services restart skhd` to see the changes. If ~/.skhdrc is a regular file, hotloading works just fine.

**Comment by koekeishiya** [comment]
implemented support for symlinks on master.

**Comment by yurrriq** [comment]
This does not seem to work when the symlink is relative, e.g. as created by [GNU Stow](https://www.gnu.org/software/stow/).

**Comment by koekeishiya** [comment]
What's the expected behaviour when the symlink is relative? We have to pass the absolutepath to the FSEvents API.

My first assumption would be that we just prepend `getenv("HOME")` to the path returned by the symlink resolver if it is a relative symlink(?). I've never used GNU Stow and I don't know how it works.

**Comment by yurrriq** [comment]
:+1: to `realpath`, though I think in the GNU Stow case, prepending `getenv("HOME")` would work too. I'll try out your change and let you know how I fare. Thanks for the patch, and the project in general, and for chunkwm!

**Comment by yurrriq** [comment]
e616840 seems to enable hotloading only if `~/.skhdrc` is a real file or an absolute symlink on startup of skhd. After that, I can swap it for the relative symlink and everything works great.

**Comment by JeanMertz** [comment]
Is hotloading still supported on latest macOS?

I've installed skhd using Brew, and have the service running. Inspecting the launchctl plist shows hotloading isn't disabled, but editing my config file still does not update the running daemon.

`skhd --reload` works as expected.

My config is symlinked to `$XDG_CONFIG_HOME/skhd/skhdrc` (the result is an absolute symlink). The directory is symlinked, not the file itself.

**Comment by koekeishiya** [comment]
Hotloading is still a thing yes. I have not tested having an actual file in a symlinked directory, so that is probably why it is not working for you. You can run skhd with the *--verbose* flag and it should print the path to the file it resolved for the hotloader.

**Comment by JeanMertz** [comment]
Thanks for the pointer @koekeishiya. I suspect you are right that this use-case is unsupported.

This is what it prints:

```
skhd: watching files for changes:
	/Users/jean/.config/skhd/skhdrc
```

The `/Users/jean/.config/skhd` directory is symlinked to somewhere else. So that implies that it starts watching the wrong file. If I edit that file, the edits take place in the original file, so no system events are sent to indicate that `/Users/jean/.config/skhd` is updated.

**Comment by kvcrawford** [comment]
Ran into this issue as well when I broke my `.skhdrc` up into multiple files. 

I have my configuration tracked in a dotfiles repo:

```bash
~/.dotfiles/skhdrc/
~/.dotfiles/skhdrc/skhdrc
~/.dotfiles/skhdrc/window
~/.dotfiles/skhdrc/space
# ...
```

Symlinked like

```bash
ln -s ~/.dotfiles/skhdrc ~/.config/skhdrc
```
