### ISSUE TITLE
skhd stays running after I stop brew services

### ISSUE THREAD

**Issue by ekilzen** [koekeishiya/skhd#198]
![image](https://user-images.githubusercontent.com/10057502/159444868-79b6bb10-cbd0-448d-888e-98ec56ce8bf9.png)
How do I stop the skhd process? I can't find it in `ps aux`.

**Comment by ekilzen** [comment]
Now I understand it...

**Comment by LVH-27** [comment]
Care to share?

**Comment by ekilzen** [comment]
@LVH-27 The `skhd` command itself is for starting a new instance of skhd, as well as `skhd -V`.

**Comment by LVH-27** [comment]
Hmm. If I recall correctly, you could run it as a service, or directly through the terminal. But what does that have to do with stopping it? I thought the issue was that, even though you stopped the brew service, skhd was still running. No?

I'm interested because I had similar behavior with yabai, the window manager, so I was hoping I could gain some insight into that here.

**Comment by ekilzen** [comment]
@LVH-27 I thought it is running, but it's not. `skhd -V` command makes it run.
