### ISSUE TITLE
SKHD completely ignoring accessibility settings

### ISSUE THREAD

**Issue by Tortus-exe** [koekeishiya/skhd#212]
I just installed SKHD. Could not find a thread which describes my issue with a clear explanation of what was going wrong so here goes. 
I installed skhd from brew following the main page. Literally two lines of code plus a settings thing, what could go wrong?
SKHD does not run on its own. 
![スクリーンショット 2022-07-11 午前12 17 45](https://user-images.githubusercontent.com/65506144/178209460-dfe247c8-9cef-4835-a446-cf5ea30cfef0.png)
I have already checked SKHD in the accessibility part of settings, and have restarted multiple times. SKHD is not running in brew. secure keyboard input something-or-other is disabled (my computer is in Japanese, forgot what it's called in English). Xcode is indeed installed. Yabai is also installed and working well! 
I've been fiddling for a while now, and will continue googling even more after I post this issue. The most I've seen thus far is a link in an issue to the mac OS custom daemon documentation, and attached to that was no clear instruction or even really a pointer. 
Also, sorry if I sound irritated. Happens when you're fiddling with cool things that you really want to work but don't. :(
Another interesting thing - when I run SKHD this is my SKHD pid file: 
![スクリーンショット 2022-07-11 午前12 23 01](https://user-images.githubusercontent.com/65506144/178210251-1f950c31-187e-4a74-a263-3269792d6075.png)
that's the whole file. weird and concerning because apparently there's supposed to be XML in there? 
Also, just in case it's relevant because it was relevant for yabai, here's csrutil status:
![スクリーンショット 2022-07-11 午前12 23 52](https://user-images.githubusercontent.com/65506144/178210388-de0e64e3-6f27-4fce-bd2b-c2c5b468e7be.png)
Any help would be greatly appreciated.

**Comment by Tortus-exe** [comment]
also the user has write access to the pid file. forgot to mention.

**Comment by giubil** [comment]
@Tortus-exe from which terminal are you running `skhd` ? 

I encountered the same issue, and it turns out that I needed to enable accessibility access for the terminal itself, not `skhd` : 

<img width="631" alt="CleanShot 2022-07-11 at 12 25 55" src="https://user-images.githubusercontent.com/9071882/178244528-fbfaf4c9-e7b3-4b9b-92d1-197f065b801c.png">

_Accessibility prompt with the name of the Terminal_

---

<img width="634" alt="CleanShot 2022-07-11 at 12 26 15" src="https://user-images.githubusercontent.com/9071882/178244599-0ac5115e-641b-45e6-9d7c-3626dfbaa53c.png">

_Skhd running after authorizing `iTerm`_

---

Let me know if that fixed it for you

**Comment by Tortus-exe** [comment]
Yes, that did fix it for me, thank you so much!!
