### ISSUE TITLE
Blacklist doesn't work for Raycast and Alfred

### ISSUE THREAD

**Issue by Sulfyderz** [koekeishiya/skhd#215]
Hello,

First thank you for your tool.

Unfortunately, `.blacklist` doesn't work for the Raycast app (a Spotlight alternative). I saw the same thing for the Alfred app ( #158). 

I've tried this:
```
.blacklist [ 
      "raycast.app" 
      "raycast"
      "/Applications/Raycast.app/Contents/MacOS/Raycast" 
      "/Applications/Raycast.app" 
]
```
The paths come from a `ps` command. Nothing changes. Raycast is not ignored. Could you help us?

Best,

**Comment by sendhil** [comment]
I hit this issue a bit ago as well and and decided I wanted to dig around and figure out what was going on. After some digging, I think the issue is that Alfred/Raycast won't work with the blacklist because skhd's blacklist code is comparing the blacklist to the current process based on data from a MacOS notification that the front app switched **and this event doesn't fire for Alfred**. The reason it doesn't fire for Alfred is I believe that Alfred (as well as Raycast and Spotlight) render their search bars with an [NSPanel](https://developer.apple.com/documentation/appkit/nspanel) that sets the `nonactivatingPanel` flag which I think is supressing this particular alert.

**Details**

I'm not that familiar with skhd's source code, but looking around I found the blacklist checking code is [here](https://github.com/koekeishiya/skhd/blob/master/src/skhd.c#L165) and [here](https://github.com/koekeishiya/skhd/blob/master/src/skhd.c#L176). I added some debug statements to the code and built my own version of the binary to do some investigating (diff of changes [here](https://gist.github.com/sendhil/02dc09f18c2ec42df7be8d0e9db6d64a)). After running my modified binary and playing around, I noticed that whenever Alfred or Spotlight came up, skhd thought that they were the previous process (i.e. the app I was using just before activating those apps). Here's a video of this in action:

![Alfred Showing Up As Previous Process](https://user-images.githubusercontent.com/437043/185540525-c6e37645-cb8f-4183-a7b0-c4bbb33d6a9b.gif)

Finding this peculiar, I looked around to see where skhd was getting the process name and I found that it was getting them from some code that was listening for a notification from MacOS(code [here](https://github.com/koekeishiya/skhd/blob/master/src/carbon.c#L37-L61)). 

I haven't dabbled in Mac or iOS programming in a long time, but I wondered if using these older APIs maybe resulted in a glitch where the notifications weren't being delivered. I created a very basic app in Xcode that just spit out details from this event (gist [here](https://gist.github.com/sendhil/1bb65c565e78b00ebbf272f8a9fb1b68)). Playing around with it, I noticed that when I would activate Alfred or Spotlight the event never fired. Here's a video of this:

![XCode App Not Detecting Alfred](https://user-images.githubusercontent.com/437043/185540559-117052c8-aae3-414f-9941-6bd5415e1aad.gif)

I still wasn't quite sure what was going on, and since neither Alfred or Spotlight are open source, I found an open source launcher called [Sol](https://github.com/ospfranco/sol)  and was able to reproduce the issue with that as well. Digging through their source code, I found that the app was using a `NSPanel`(code [here](https://github.com/ospfranco/sol/blob/main/macos/sol-macOS/views/Panel.swift#L9)) and it set a property called `nonactivatingPanel`. According to Apple's documentation([link](https://developer.apple.com/documentation/appkit/nswindow/stylemask/1644696-nonactivatingpanel)) this property makes it so an `NSPanel` doesn't activate the owning app. 

Wanting to see if I could get a little more data, I used Accessibility Inspector on Alfred,Spotlight and Sol and all three indicated that they were `AXSystemDialog` which led me to [this code](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.7.sdk/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/Headers/AXRoleConstants.h#L234) which led me to [this](https://developer.apple.com/documentation/applicationservices/kaxsystemdialogsubrole) doc page which seemed to hint that Alfred/Spotlight set things up similarly to Sol. For reference, here's the accessibility inspector output for [Alfred](https://user-images.githubusercontent.com/437043/185537181-2579ff4f-4523-4916-a531-60741b822bdb.png), [Spotlight](https://user-images.githubusercontent.com/437043/185537393-069e94fa-956a-4466-9ca8-c0350d0ec3c9.png), and [Sol](https://user-images.githubusercontent.com/437043/185537272-8abbc91f-d2c7-4983-b15a-04c3c1ef72ae.png).

**Comment by sendhil** [comment]
I should add, I'm not sure this is fixable unless there's some other event that skhd can use instead of `kEventAppFrontSwitched` that will provide the data this event seems to be missing.  Looking through the [options](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/CarbonEvents.h#L4738-L4768) - I'm not sure anything really jumps out at me (caveat - I'm not a Mac developer so someone who is might have a better idea).

**Comment by Sulfyderz** [comment]
Hello @sendhil , 

Thank you for your detailed answers and your great efforts!

I thought the same thing. That Raycast or Alfred rely on a notification system whereas Skhd does not.

Finally, I have optimized my hotkeys. Everything on the left side (fn, ctrl, option and cmd) are for [Yabai](https://github.com/koekeishiya/yabai), on the right side (cmd and option) are for apps like Raycast. We can do this with the latest version of Skhd. For instance, the left cmd is called with "lcmd".
