### ISSUE TITLE
Some SKHD short keys work while some do not

### ISSUE THREAD

**Issue by MrNeth** [koekeishiya/skhd#240]
Most skhd short keys are working, but the short keys to move to a different space is not, the short key below are not working:

#cycle through desktops
```
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
```

when i run `skhd -V` and try to use the above shortkeys i get this error:

`cannot focus space due to an error with the scripting-addition.`

The following 2 short key commands work but I still get errors in `skhd -V` : 

**SKHD config 1**
```
cmd - tab : yabai -m window --focus stack.prev || yabai -m window --focus prev || yabai -m window --focus last
cmd - tab : yabai -m window --focus stack.next || yabai -m window --focus next || yabai -m window --focus first

```
**ERROR 1**
```
could not locate the prev stacked window.
could not locate the prev managed window.
```

**SKHD config 2**
```
lctrl + alt - k : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
lctrl + alt - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0
```

**ERROR 2**
```
cannot locate a bsp node fence.
could not locate the prev managed window.
```

**Comment by darklyspaced** [comment]
Probably due to the fact that your yabai scripting addition did not attach properly as said by the errors. Remove it and follow the instructions at the wiki again while also updating yabai and skhd itself and disabling secure key entry everywhere (iterm and terminal are usually the culprits).

1. Upgrade Yabai & skhd
2. Ensure that System Integrity Protection settings are disabled
3. Reattach [yabai scripting addition](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition)
4. Disable secure key entry on Terminal (and other culprits; iTerm2, Alacritty et cetera)

**Comment by MrNeth** [comment]
UPDATE - I fixed the many issues here by installing from [head](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD))
