### ISSUE TITLE
Ability to make all windows go full screen via a hotkey?

### ISSUE THREAD

**Issue by shiyanshirani** [koekeishiya/skhd#273]

**Comment by pawnhearts** [comment]
weord idea. can be done via applescript anyway

**Comment by shiyanshirani** [comment]
I'm not talking about Apple native full screen, I'm talking `yabai -m window --toggle zoom-fullscreen` for all applications. I need this when I'm using my 13' screen where tiling squishes everything.

**Comment by koekeishiya** [comment]
You can use the following command to toggle zoom-fullscreen for all windows on the currently active space: `yabai -m query --windows --space | jq '.[].id' | xargs -I{} yabai -m window {} --toggle zoom-fullscreen`

If you always want windows to be fullscreen you can just use the `stack` layout instead of `bsp` though.

**Comment by shiyanshirani** [comment]
thank you @koekeishiya, I was looking for this.
