### ISSUE TITLE
Error with the scripting-addition since MacOS Somona 14.0

### ISSUE THREAD

**Issue by Blebesquefee** [koekeishiya/skhd#304]
Hi everyone !

First thanks for this amazing project that I daily use !

Since Somona 14.0 and after update yabai and skhd, i cannot move around spaces even if I disabled “Click to focus on wallpaper”
I tried to restart my mac but nothing seems to change.

Here is my config and my err.log file

[skhd.err.log](https://github.com/koekeishiya/skhd/files/12749484/skhd.err.log)

[skhdrc.txt](https://github.com/koekeishiya/skhd/files/12747323/skhdrc.txt)

[iTerm.txt](https://github.com/koekeishiya/skhd/files/12747325/iTerm.txt)

**Comment by walshg3** [comment]
i am also having issues with moving spaces

**Comment by mac137** [comment]
the same issue

**Comment by sk0gen** [comment]
I guess those error are related with 'Yabai' 
[Focus Error](https://github.com/koekeishiya/yabai/blob/8c338044bbbcafcf27dc21de29534393eee9cfbe/src/message.c#L1612C1-L1612C1)

**Comment by tmarkanov** [comment]
I've had the same issue on Yabai 5.0.9 + Sonoma + M2.
For me the solution was updating my `sudoers.d/yabai` - namely updating the sha256 hash, which has changed since the previous version.

More information on updating the hash can be found [on Yabai wiki](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition).

**Comment by Blebesquefee** [comment]
Thanks @tmarkanov for the solution !

1. ```brew upgrade yabai && brew upgrade skhd```
2. Updating ```sudoers.d/yabai``` file
-> All things seems to work properly
