### ISSUE TITLE
Can't do either fullscreen in bsp

### ISSUE THREAD

**Issue by Ciel-MC** [koekeishiya/skhd#310]
When I run the command `yabai -m window --toggle (zoom|native)-fullscreen`, it works fine in the terminal, but not when dispatched with skhd, there it just prints `cannot apply grid layout to a managed window.` for any tiling window, and I have no idea why that might be because other things like toggle splits work.

M1 Pro Ventura 13.6

**Comment by tjex** [comment]
can you post your full yabai and skhd conf? Or link a gist?
I can toggle native full screen from skhd:

https://github.com/tjex/dotfiles/blob/mac/.config/skhd/skhdrc

**Comment by Ciel-MC** [comment]
> can you post your full yabai and skhd conf? Or link a gist?
> 
> I can toggle native full screen from skhd:
> 
> 
> 
> https://github.com/tjex/dotfiles/blob/mac/.config/skhd/skhdrc

I'll check when I have time, but I doubt it's the config's problem? Since the exact same command works in terminal but not when run by skhd.

**Comment by tjex** [comment]
Maybe, maybe not. Considering anyone helping doesn't have access to your machine, we have to pick through the haystack to find the needle. Config files / logs / output are our way into the system from afar. With them it can be possible to diagnose problems arising from honest and simple mistakes. And considering how little effort it takes to share a config, it's a worthy task. 

-> Also, because I'm on 13.5 and it works fine for me.

**Comment by tjex** [comment]
So it looks like you've mapped `ctrl -f` twice. 
I guess this is it :~)

**Comment by Ciel-MC** [comment]
> So it looks like you've mapped `ctrl -f` twice. I guess this is it :~)

I feel so dumb rn. I guess it was perhaps a part of the default config? Anyway, that worked, thanks lol.

**Comment by tjex** [comment]
no worries. We're all caught multiple times by such things! 👍
