### ISSUE TITLE
SKHD not working at all

### ISSUE THREAD

**Issue by evan01** [koekeishiya/skhd#41]
I have...

- Enabled accessibility access
- Running `brew services list` tells me that skhd is working
- Secure keyboard entry is disabled
- chunkwm is working
- Skdhrc is present and valid

And I'm not sure at all why everything is still failing. Could it be that one of my chunkwm plugins failed to load?

**Comment by koekeishiya** [comment]
Can you try to stop both services and run chunkwm and skhd manually inside a terminal session. This should allow you to see any potential errors / warnings that may have been printed to stdout / stderr

**Comment by evan01** [comment]
Oh! Looks like skhd is working and just **chunkwm** isn't working. I'm getting... 

> invalid selector 'fullscreen.

**Comment by tobiasljungstrom** [comment]
Adding to reasons why skhd might not work and how to fix:

After stopping the brew service with `brew service stop skhd` and starting the program again with debugging enabled, `skhd -V` i finally noticed the following at the end of the config readout:

```
hotkey :: #13 {
#13:24 undeclared identifier
```

This was due to an extra space being present in the config file, right at the end of one of the lines. Removing this made everything work again.
