### ISSUE TITLE
Passthrough `->` not working

### ISSUE THREAD

**Issue by darvelo** [koekeishiya/skhd#43]
I have a `switcher` mode I use to switch desktops, and in `khd` I used to map a key to the Mission Control hotkey via the passthrough mechanism. In `skhd` I'm trying to do this as well:

```
:: switcher @ : chunkc border::color 0xddbdd322
switcher <  ctrl - left    -> :   true
switcher <  ctrl - right   -> :   true
switcher <  w :   qes -k "ctrl - left"
switcher <  e :   qes -k "ctrl - right"
```

Unfortunately the `w` and `e` hotkeys here don't trigger the desktop switching behavior as they did in `khd`.

**Comment by koekeishiya** [comment]
So the issue here is that the switcher mode is set to basically ignore all keypresses that are not bound for that mode. The way this currently works, is that if *@* is used, OR the bind is not a passthrough, we ignore the keypress.

We could make it so that a bind marked as passthrough will take precedence over *@*. This is probably how it should work.

**Comment by koekeishiya** [comment]
fixed on master.

**Comment by darvelo** [comment]
Thank you!
