### ISSUE TITLE
Support key aliases / hyper

### ISSUE THREAD

**Issue by robertgzr** [koekeishiya/skhd#6]
I like binding all wm related commands to a _hyper mod_ (cmd + alt + ctrl + shift) so I find myself having to type that out for every new hotkey:
```
...
cmd + alt + ctrl + shift - h : chunkc tiling::window --focus west
cmd + alt + ctrl + shift - j : chunkc tiling::window --focus south
cmd + alt + ctrl + shift - k : chunkc tiling::window --focus north
cmd + alt + ctrl + shift - l : chunkc tiling::window --focus east
...
```

It would be nice to have a way to define aliases like: 
```
hyper := cmd + alt + ctrl + shift
hyper - h : chunkc tiling::window --focus west
```

Alternatively having `hyper` available as a mod key would probably also work...

**Comment by koekeishiya** [comment]
> It would be nice to have a way to define aliases

Agreed, no ETA for now though.

**Comment by koekeishiya** [comment]
I've been thinking some more about this, and adding a built-in hyper keyword seems like the more appropriate solution.

**Comment by tigger04** [comment]
It seems a curious decision to _hard code_ the definition of hyper. Not every hyper key is the same.

For example, I prefer to use `cmd + alt + ctrl` - **but not shift** - to be my hyper key, which I have mapped in karabiner.

Why?

Because if hyper is matched to _all_ available modifier keys, I have excluded them from being used _with_ they hyper key, much limiting its usefulness.

An example from my config:

```
cmd + ctrl + alt - m : open -a whatsapp
cmd + ctrl + alt + shift - m : open -a signal

```

As you can see I have the same problem as the original post. Wouldn't it be nice to be able to define an alias, and write:


```
hyper - m : open -a whatsapp
hyper + shift - m : open -a signal

```

Obviously I could no longer use hyper as the name of my alias in the above example as that is now hardcoded to mean something specific. But allowing an alias to be defined in the config, without disturbing the current meaning of hyper in the code, would preserve backward compatibility while allowing for some flexibility.

Not all hyper keys are the same!

**Comment by Miigon** [comment]
Agreed with @tigger04.

**Comment by koekeishiya** [comment]
I don't have time to do support for this project. Feel free to implement said change on your own,
