### ISSUE TITLE
key blocked?

### ISSUE THREAD

**Issue by nolledge** [koekeishiya/skhd#64]
Hi,
this should be a common problem, but I could not find an answer to it:

I am using this configuration to navigate between windows:
```

# Navigation
alt - h : chunkc tiling::window --focus west
alt - j : chunkc tiling::window --focus south
alt - k : chunkc tiling::window --focus north
alt - l : chunkc tiling::window --focus east

```

The configuration for alt + l seems to block my "@" key. Do I need to use a different key mapping to make it available again?

**Comment by dominiklohmann** [comment]
If `alt - j` is how you usually type the character `@`—yes, you would have to remap either `@` or the command. You cannot expect skhd to know when to execute the mapped command versus forwarding the key so you get the desired input. 

Personally, this is why I stay away from `alt` and `cmd` modifier only mappings and mostly use `fn`, `cmd + ctrl` or `shift + ctrl`, since neither of these have system default mappings (except for `ctrl + left mouse button` being `right mouse button`, which cannot be remapped, and `fn + arrow key` is `home/end/pgup/pgdown`).

**Comment by nolledge** [comment]
Thank you. That makes sense. I was just a little confused because this mapping is part of the sample skhdrc.

**Comment by dominiklohmann** [comment]
The example is just that—an example. And it's a bad one for US and german mac keyboard layouts in my experience, after having tested both. Best just start with an empty configuration and go through this file and create your mappings based on your needs: https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md

**Comment by koekeishiya** [comment]
Closing this as a non-issue.

Thanks again for continued support @dominiklohmann, much appreciated!
