### ISSUE TITLE
Does not appear to respect system keyboard layout

### ISSUE THREAD

**Issue by danpalmer** [koekeishiya/skhd#69]
Given a configuration of:

```
cmd - j : chunkc tiling::window --focus prev
```

When using the Dvorak Cmd-Qwerty layout on macOS, pressing "Cmd+C" focuses to the previous window.

This should be interpreted as "Cmd+C", not "Cmd+J".

**Comment by dominiklohmann** [comment]
See #1.

**Comment by koekeishiya** [comment]
I'm not familiar with `dvorak Cmd-Qwerty` layout, but standard `dvorak` has `j` located where `c` would be in a standard `qwerty` setup. We lookup the currently selected keyboard-layout and translate keycodes to the string representation it has for that layout to define our mapping. See https://github.com/koekeishiya/skhd/blob/master/src/locale.c#L62

I also confirmed during development of #59 that changing my input-source would cause the bindings to change. Is the issue that you are using a `dvorak` layout, but toggled into `qwerty`-mode or something? And because of that, **skhd** treats it as `dvorak` when it should've been handled as `qwerty`?
