### ISSUE TITLE
Add function to bypass the following shotcut keypress

### ISSUE THREAD

**Issue by brorbw** [koekeishiya/skhd#79]
Im looking for a feature that temporally disables the shortcuts in skhd.
The use would be, a shortcut that disables the functionality of skhd for the next modifier key combination and just passes it to the OS. This would allow me to use stuff like, [alt + x] in emacs and lots more shortcuts native to the OS.

If this is already possible, could you guide me though the steps to set it up. If not, maybe you could point me in the correct direction.

EDIT: It should have been labeled, improvement. I can't edit it now.

**Comment by koekeishiya** [comment]
This is currently not possible as far as I know. Maybe you could be creative with the passthrough functionality and modes, but I haven't thought it through, and it wasn't particularly designed for this use.

A common *"solution"* is to have a way to enter passthrough mode, essentially deactivating *skhd* until you press some key to reactivate it. See https://github.com/koekeishiya/skhd/issues/71 for how-to do that approach.

For what you are suggesting, you'd need to somehow propagate the information to ignore the next keypress into this function: https://github.com/koekeishiya/skhd/blob/master/src/skhd.c#L158

My first though would be to have some sort of way to identify this behaviour in the grammar. This would allow the user to specify their own bind to cause *skhd* to ignore the upcoming keyevent.
Expanding the concept of an *internal action* recognized with the `;` token to handle various types of actions instead of expecting a *mode identifier* could be a starting point. 

I'm not sure if this is something I want to implement in *skhd* upstream, but I'd be happy to help you with information you'd need to make these tweaks in a personal fork.
