### ISSUE TITLE
All hotkeys are ignored except for fm+mouse bindings, which are still working

### ISSUE THREAD

**Issue by suprichk** [koekeishiya/skhd#88]
After using skhd with chunkwm successfully for a couple of days, this morning the hotkeys have randomly stopped working and are interpreted as language-related keyboard shortcuts from programs (i.e. alt + t doesn't float the focused window but writes a ™). 
I restarted the service with `brew services restart skhd` a couple of times without success.
fn + mouse click shortcuts to move and resize windows are still working

**Comment by dominiklohmann** [comment]
Run `brew services stop skhd` and then run `skhd --verbose` in your terminal to see a detailed log of what's happening. This will help you debug your issue. 

It's quite likely that your pid file got stuck because your computer crashed (`rm /tmp/skhd_$USER.pid` to remove it) or that something in your configuration file is wrong.

Note: Running skhd from your terminal instead of a launch agent (via brew services) might prompt for accessibility permissions for your terminal app. You should remove these permissions again after you're done.

**Comment by koekeishiya** [comment]
> It's quite likely that your pid file got stuck because your computer crashed (rm /tmp/skhd_$USER.pid to remove it) or that something in your configuration file is wrong.

I don't think this is likely. *skhd* uses an advisory lock, which means that the file is only locked while the process has an open handle. If the process terminates in any way the system will properly perform cleanup. The mere existence of the file itself does not matter.

**Comment by suprichk** [comment]
> > It's quite likely that your pid file got stuck because your computer crashed (rm /tmp/skhd_$USER.pid to remove it) or that something in your configuration file is wrong.
> 
> I don't think this is likely. _skhd_ uses an advisory lock, which means that the file is only locked while the process has an open handle. If the process terminates in any way the system will properly perform cleanup. The mere existence of the file itself does not matter.

It fixed itself after a full computer reboot! :)
