### ISSUE TITLE
skhd stopped working under brew services/mojave

### ISSUE THREAD

**Issue by igorclark** [koekeishiya/skhd#94]
Hi there,

Until very recently, `skhd` was working just fine under `brew services`, using `tmux` inside [Alacritty](https://github.com/jwilm/alacritty) as my main terminal application.

I ran a couple of software updates this week (including this morning when I did mojave 10.14.6 supplemental update 2 and `brew upgrade`), and now `skhd` is having problems.

It works fine when run directly in a terminal inside `tmux` (inside Alacritty), but when running from `brew services start`, even directly by `launchd` after a fresh reboot, it doesn't send any commands to `chunkwm` or `yabai`. (I tried both, and tried sending tiling commands to both of them directly from the shell, which works fine either way.) Instead, when running under `brew services`, for every keyboard combination I press from `.skhdrc`, I get an error in the `skhd` log saying `open terminal failed: not a terminal`.

Googling suggests that's related to `tmux`, so I don't know if it's a problem getting something into the log file or something, but the error appears whether the tmux window (either inside Alacritty or Terminal.app) is focused or not, so I'm not sure what's going on there.

Any ideas would be very welcome! Thanks 😊

**Comment by ianmjones** [comment]
I'm a new user (as of today), but had the same problem when using `skhd` via `brew services start skhd`, and basically any other means.

Then I noticed that `skhd -V` said it was going to use `~/.skhdrc` and then complained about not being able to use it. Which was because I was wanting to use `~/.config/skhd/skhdrc` as that is supposed to be supported.

So I moved my config to `~/.skhdrc` and now both manual and the `brew services start skhd` method of using `skhd` work, including after reboot.

I don't know if that helps given that @igorclark already mentions `.skhdrc`? `¯\\_(ツ)_/¯

Only other possible reason I can think of is permissions of (path to) `~/.config/skhd/skhdrc` in my case do not include any "other" permissions, although it's a bit more complicated than that as I use `stow`. But that's grasping at straws.

**Comment by igorclark** [comment]
Hi @ianmjones, thanks for the message! I don't think this is the problem I was having, as my `.skhdrc` was working fine before the updates, and `skhd` itself still works with it when run directly  from a shell. Appreciate the input though. Will double-check this when I get a new macOS or `brew` upgrade. Cheers.

**Comment by zioroboco** [comment]
@igorclark I also started having this issue after a restart (`skhd` not working as a service, but working when run directly).

Going into `System Preferences > Security & Privacy > Privacy` and then unchecking and rechecking `skhd` in the Accessibility permissions fixed it for me. 🤞

**Comment by johnallen3d** [comment]
Thanks @igorclark! Same scenario for me and toggling `skhd` under `Accessibility > Privacy` did the trick for me.

**Comment by igorclark** [comment]
Hi @zioroboco and @johnallen3d, glad you're getting somewhere but this doesn't work for me. Tried it quite a few times. Also just updated to latest Mojave supplemental update and that didn't work either :-(

**Comment by JensenJiang** [comment]
hey, I just ran into exactly the same problem(upgraded to 10.14.6 update2, and skhd failed) and this is how I fixed:
1. `brew uninstall skhd`
2. Remove the entry of skhd in `System Preferences > Security & Privacy > Privacy`
3. `brew install skhd`
4. Reboot your mac, since it won't ask you for permission again without reboot;
5. After login, skhd will request permission.

Hope it works for you too :-)

**Comment by igorclark** [comment]
Hi folks, sorry I never got round to replying @JensenJiang but unfortunately that didn't work for me either.

However, I just updated to the latest Mojave Security Update and lo and behold, `skhd` and `chunkwm` via `brew services` started working again. No idea why, which makes me slightly nervous that it'll all break again when I do a `brew update` or another MacOS update at some point, but for now it's working as expected. Hooray.
